name: desk-booking-app

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: desk-booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
