// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723181610_AddWorkspaceBookings")]
    partial class AddWorkspaceBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityWorkspace", b =>
                {
                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenities_id");

                    b.Property<Guid>("WorkspacesId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspaces_id");

                    b.HasKey("AmenitiesId", "WorkspacesId")
                        .HasName("pk_amenity_workspace");

                    b.HasIndex("WorkspacesId")
                        .HasDatabaseName("ix_amenity_workspace_workspaces_id");

                    b.ToTable("amenity_workspace", (string)null);
                });

            modelBuilder.Entity("BookingDesk", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("DesksId")
                        .HasColumnType("uuid")
                        .HasColumnName("desks_id");

                    b.HasKey("BookingId", "DesksId")
                        .HasName("pk_booking_desk");

                    b.HasIndex("DesksId")
                        .HasDatabaseName("ix_booking_desk_desks_id");

                    b.ToTable("booking_desk", (string)null);
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_room_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_bookings_workspace_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Domain.Workspaces.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_amenities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_amenities_name");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("Domain.Workspaces.Desk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_desks");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_desks_workspace_id");

                    b.ToTable("desks", (string)null);
                });

            modelBuilder.Entity("Domain.Workspaces.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_rooms_workspace_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("MaxBookingDuration")
                        .HasColumnType("interval")
                        .HasColumnName("max_booking_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_name");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Domain.Workspaces.WorkspacePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_photos");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_photos_url");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_photos_workspace_id");

                    b.ToTable("workspace_photos", (string)null);
                });

            modelBuilder.Entity("AmenityWorkspace", b =>
                {
                    b.HasOne("Domain.Workspaces.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amenity_workspace_amenities_amenities_id");

                    b.HasOne("Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amenity_workspace_workspaces_workspaces_id");
                });

            modelBuilder.Entity("BookingDesk", b =>
                {
                    b.HasOne("Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_desk_bookings_booking_id");

                    b.HasOne("Domain.Workspaces.Desk", null)
                        .WithMany()
                        .HasForeignKey("DesksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_desk_desks_desks_id");
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Domain.Workspaces.Room", "Room")
                        .WithOne()
                        .HasForeignKey("Domain.Bookings.Booking", "RoomId")
                        .HasConstraintName("fk_bookings_rooms_room_id");

                    b.HasOne("Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_workspaces_workspace_id");

                    b.Navigation("Room");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Workspaces.Desk", b =>
                {
                    b.HasOne("Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("Desks")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desks_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Workspaces.Room", b =>
                {
                    b.HasOne("Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("Rooms")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Workspaces.WorkspacePhoto", b =>
                {
                    b.HasOne("Domain.Workspaces.Workspace", "Workspace")
                        .WithMany("Photos")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_photos_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Workspaces.Workspace", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Desks");

                    b.Navigation("Photos");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
